In [1]:
# importing of libaries
import pandas as pd
import numpy as np

In [2]:
# reading dataset
df1 = pd.read_excel("Bank_Churn_Messy.xlsx", sheet_name = 0)
df2 = pd.read_excel("Bank_Churn_Messy.xlsx", sheet_name = 1)
# merging both dataset to one
df = pd.merge(df1, df2, on = ["CustomerId", "Tenure"], how = "inner")
df.head(20)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,15634602,Hargrave,619,FRA,Female,42.0,2,€101348.88,€0.0,1,Yes,Yes,1
1,15634602,Hargrave,619,FRA,Female,42.0,2,€101348.88,€0.0,1,Yes,Yes,1
2,15647311,Hill,608,Spain,Female,41.0,1,€112542.58,€83807.86,1,Yes,Yes,0
3,15619304,Onio,502,French,Female,42.0,8,€113931.57,€159660.8,3,No,No,1
4,15701354,Boni,699,FRA,Female,39.0,1,€93826.63,€0.0,2,No,No,0
5,15737888,Mitchell,850,Spain,Female,43.0,2,€79084.1,€125510.82,1,Yes,Yes,0
6,15574012,Chu,645,Spain,Male,44.0,8,€149756.71,€113755.78,2,No,No,1
7,15592531,Bartlett,822,France,Male,50.0,7,€10062.8,€0.0,2,Yes,Yes,0
8,15656148,Obinna,376,Germany,Female,29.0,4,€119346.88,€115046.74,4,No,No,1
9,15792365,He,501,French,Male,44.0,4,€74940.5,€142051.07,2,Yes,Yes,0
10,15592389,H?,684,France,Male,27.0,2,€71725.73,€134603.88,1,Yes,Yes,0
11,15767821,Bearce,528,French,Male,31.0,6,€80181.12,€102016.72,2,No,No,0
12,15737173,Andrews,497,Spain,Male,24.0,3,€76390.01,€0.0,2,No,No,0
13,15632264,Kay,476,FRA,Female,34.0,10,€26260.98,€0.0,2,No,No,0
14,15691483,Chin,549,France,Female,25.0,5,€190857.79,€0.0,2,No,No,0
15,15600882,Scott,635,Spain,Female,35.0,7,€65951.65,€0.0,2,Yes,Yes,0
16,15643966,Goforth,616,Germany,Male,45.0,3,€64327.26,€143129.41,2,Yes,Yes,0
17,15737452,Romeo,653,Germany,Male,58.0,1,€5097.67,€132602.88,1,No,No,1
18,15788218,Henderson,549,Spain,Female,24.0,9,€14406.41,€0.0,2,Yes,Yes,0
19,15661507,Muldrow,587,Spain,Male,45.0,6,€158684.81,€0.0,1,No,No,0

In [3]:
# inspecting the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10004 entries, 0 to 10003
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10004 non-null  int64
 1   Surname          10001 non-null  object
 2   CreditScore      10004 non-null  int64
 3   Geography        10004 non-null  object
 4   Gender           10004 non-null  object
 5   Age              10001 non-null  float64
 6   Tenure           10004 non-null  int64
 7   EstimatedSalary  10004 non-null  object
 8   Balance          10004 non-null  object
 9   NumOfProducts    10004 non-null  int64
 10  HasCrCard        10004 non-null  object
 11  IsActiveMember   10004 non-null  object
 12  Exited           10004 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 1016.2+ KB

In [4]:
# checking for missing values
df.isnull().sum()

CustomerId         0
Surname            3
CreditScore        0
Geography          0
Gender             0
Age                3
Tenure             0
EstimatedSalary    0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
Exited             0
dtype: int64

In [5]:
# checking for duplicates values
print(df.duplicated().sum())

4

In [6]:
# handling of missing values
df.dropna(inplace=True)
df.isnull().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
EstimatedSalary    0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
Exited             0
dtype: int64

In [7]:
# handling duplicates values
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [8]:
df["Geography"].unique()

array(['FRA', 'Spain', 'French', 'France', 'Germany'], dtype=object)

In [9]:
df["Geography"].replace({
    "FRA": "France",
    "French": "France"
}, inplace=True)

df["Geography"].unique()

C:\Users\USER\AppData\Local\Temp\ipykernel_11200\3315793429.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Geography"].replace({

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
def clean_currency(x):
    if isinstance(x, str):
        return x.replace("€", "")
    return x
df["EstimatedSalary"] = df["EstimatedSalary"].apply(clean_currency)
df["Balance"] = df["Balance"].apply(clean_currency)
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,15634602,Hargrave,619,France,Female,42.0,2,101348.88,0.0,1,Yes,Yes,1
2,15647311,Hill,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,Yes,0
3,15619304,Onio,502,France,Female,42.0,8,113931.57,159660.8,3,No,No,1
4,15701354,Boni,699,France,Female,39.0,1,93826.63,0.0,2,No,No,0
5,15737888,Mitchell,850,Spain,Female,43.0,2,79084.1,125510.82,1,Yes,Yes,0

In [11]:
# converting excited column with (1- yes, 0 - no)
df["Exited"] = df["Exited"].replace({
    0:"No",
    1: "Yes"
})
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,15634602,Hargrave,619,France,Female,42.0,2,101348.88,0.0,1,Yes,Yes,Yes
2,15647311,Hill,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,Yes,No
3,15619304,Onio,502,France,Female,42.0,8,113931.57,159660.8,3,No,No,Yes
4,15701354,Boni,699,France,Female,39.0,1,93826.63,0.0,2,No,No,No
5,15737888,Mitchell,850,Spain,Female,43.0,2,79084.1,125510.82,1,Yes,Yes,No

In [12]:
# filtering customer with high credit score 
high_customer_credit_score = df[df["CreditScore"] >= 700]
high_customer_credit_score

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
5,15737888,Mitchell,850,Spain,Female,43.0,2,79084.1,125510.82,1,Yes,Yes,No
7,15592531,Bartlett,822,France,Male,50.0,7,10062.8,0.0,2,Yes,Yes,No
20,15568982,Hao,726,France,Female,24.0,6,54724.03,0.0,2,Yes,Yes,No
21,15577657,McDonald,732,France,Male,41.0,8,170886.17,0.0,2,Yes,Yes,No
25,15625047,Yen,846,France,Female,38.0,5,187616.16,0.0,1,Yes,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15719294,Wood,800,France,Female,29.0,2,167773.55,0.0,2,No,No,No
9996,15606229,Obijiaku,771,France,Male,39.0,5,96270.64,0.0,2,No,No,No
9998,15584532,Liu,709,France,Female,36.0,7,42085.58,0.0,1,Yes,Yes,Yes
9999,15682355,Sabbatini,772,Germany,Male,42.0,3,92888.52,75075.31,2,No,No,Yes
10000,15628319,Walker,792,France,Female,28.0,4,38190.78,130142.79,1,No,No,No

In [13]:
# finding active member in germany
active_member_in_germany = df[(df["Geography"] == "Germany") & (df["IsActiveMember"] == "Yes")]
active_member_in_germany

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
16,15643966,Goforth,616,Germany,Male,45.0,3,64327.26,143129.41,2,Yes,Yes,No
27,15736816,Young,756,Germany,Male,36.0,2,170041.95,136815.64,1,Yes,Yes,No
40,15585768,Cameron,582,Germany,Male,41.0,6,178074.04,70349.48,2,Yes,Yes,No
46,15754849,Tyler,776,Germany,Female,32.0,4,126517.46,109421.13,2,Yes,Yes,No
47,15602280,Martin,829,Germany,Female,27.0,9,119708.21,112045.67,1,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9951,15638494,Salinas,625,Germany,Female,39.0,10,96444.88,129845.26,1,Yes,Yes,No
9961,15681026,Lucciano,795,Germany,Female,33.0,9,120853.83,104552.72,1,Yes,Yes,Yes
9982,15672754,Burbidge,498,Germany,Male,42.0,3,53445.17,152039.7,1,Yes,Yes,Yes
9985,15696175,Echezonachukwu,602,Germany,Male,35.0,7,51695.41,90602.42,2,Yes,Yes,No
9987,15581736,Bartlett,673,Germany,Male,47.0,1,34047.54,183579.54,2,Yes,Yes,No

In [14]:
df.groupby("Geography")["IsActiveMember"].value_counts()

Geography  IsActiveMember
France     Yes               2590
           No                2423
Germany    No                1261
           Yes               1247
Spain      Yes               1312
           No                1164
Name: count, dtype: int64

In [15]:
churned_customer = df[df["Exited"] == "Yes"]
churned_customer

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,15634602,Hargrave,619,France,Female,42.0,2,101348.88,0.0,1,Yes,Yes,Yes
3,15619304,Onio,502,France,Female,42.0,8,113931.57,159660.8,3,No,No,Yes
6,15574012,Chu,645,Spain,Male,44.0,8,149756.71,113755.78,2,No,No,Yes
8,15656148,Obinna,376,Germany,Female,29.0,4,119346.88,115046.74,4,No,No,Yes
17,15737452,Romeo,653,Germany,Male,58.0,1,5097.67,132602.88,1,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,15672754,Burbidge,498,Germany,Male,42.0,3,53445.17,152039.7,1,Yes,Yes,Yes
9983,15768163,Griffin,655,Germany,Female,46.0,7,115146.4,137145.12,1,No,No,Yes
9992,15769959,Ajuluchukwu,597,France,Female,53.0,4,69384.71,88381.21,1,No,No,Yes
9998,15584532,Liu,709,France,Female,36.0,7,42085.58,0.0,1,Yes,Yes,Yes
9999,15682355,Sabbatini,772,Germany,Male,42.0,3,92888.52,75075.31,2,No,No,Yes

In [19]:
# creating a new dataframe 
rating = pd.DataFrame({
    "CustomerId": df["CustomerId"].unique(),
    "ServiceRating": np.random.randint(1, 6, len(df["CustomerId"].unique()))
    
})
df= df.merge(rating, on= "CustomerId", how="left")
df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,ServiceRating_x,ServiceRating_y
0,15634602,Hargrave,619,France,Female,42.0,2,101348.88,0.0,1,Yes,Yes,Yes,4,1
1,15647311,Hill,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,Yes,No,3,5
2,15619304,Onio,502,France,Female,42.0,8,113931.57,159660.8,3,No,No,Yes,2,4
3,15701354,Boni,699,France,Female,39.0,1,93826.63,0.0,2,No,No,No,3,5
4,15737888,Mitchell,850,Spain,Female,43.0,2,79084.1,125510.82,1,Yes,Yes,No,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,15606229,Obijiaku,771,France,Male,39.0,5,96270.64,0.0,2,No,No,No,2,3
9993,15569892,Johnstone,516,France,Male,35.0,10,101699.77,57369.61,1,Yes,Yes,No,2,4
9994,15584532,Liu,709,France,Female,36.0,7,42085.58,0.0,1,Yes,Yes,Yes,4,3
9995,15682355,Sabbatini,772,Germany,Male,42.0,3,92888.52,75075.31,2,No,No,Yes,2,3
9996,15628319,Walker,792,France,Female,28.0,4,38190.78,130142.79,1,No,No,No,5,2

In [20]:
avg_credit_score = df.groupby("Geography")["CreditScore"].mean()
avg_credit_score

Geography
France     649.690604
Germany    651.484450
Spain      651.324717
Name: CreditScore, dtype: float64